# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/code/games/sokoban

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/code/games/sokoban

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/code/games/sokoban/CMakeFiles /home/michael/code/games/sokoban/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/code/games/sokoban/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sokoban

# Build rule for target.
sokoban: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sokoban
.PHONY : sokoban

# fast build rule for target.
sokoban/fast:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/build
.PHONY : sokoban/fast

level_reader.o: level_reader.c.o

.PHONY : level_reader.o

# target to build an object file
level_reader.c.o:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/level_reader.c.o
.PHONY : level_reader.c.o

level_reader.i: level_reader.c.i

.PHONY : level_reader.i

# target to preprocess a source file
level_reader.c.i:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/level_reader.c.i
.PHONY : level_reader.c.i

level_reader.s: level_reader.c.s

.PHONY : level_reader.s

# target to generate assembly for a file
level_reader.c.s:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/level_reader.c.s
.PHONY : level_reader.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/main.c.s
.PHONY : main.c.s

maths/maths.o: maths/maths.c.o

.PHONY : maths/maths.o

# target to build an object file
maths/maths.c.o:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/maths/maths.c.o
.PHONY : maths/maths.c.o

maths/maths.i: maths/maths.c.i

.PHONY : maths/maths.i

# target to preprocess a source file
maths/maths.c.i:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/maths/maths.c.i
.PHONY : maths/maths.c.i

maths/maths.s: maths/maths.c.s

.PHONY : maths/maths.s

# target to generate assembly for a file
maths/maths.c.s:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/maths/maths.c.s
.PHONY : maths/maths.c.s

objects/cube.o: objects/cube.c.o

.PHONY : objects/cube.o

# target to build an object file
objects/cube.c.o:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/objects/cube.c.o
.PHONY : objects/cube.c.o

objects/cube.i: objects/cube.c.i

.PHONY : objects/cube.i

# target to preprocess a source file
objects/cube.c.i:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/objects/cube.c.i
.PHONY : objects/cube.c.i

objects/cube.s: objects/cube.c.s

.PHONY : objects/cube.s

# target to generate assembly for a file
objects/cube.c.s:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/objects/cube.c.s
.PHONY : objects/cube.c.s

utils/gl_utils.o: utils/gl_utils.c.o

.PHONY : utils/gl_utils.o

# target to build an object file
utils/gl_utils.c.o:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/utils/gl_utils.c.o
.PHONY : utils/gl_utils.c.o

utils/gl_utils.i: utils/gl_utils.c.i

.PHONY : utils/gl_utils.i

# target to preprocess a source file
utils/gl_utils.c.i:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/utils/gl_utils.c.i
.PHONY : utils/gl_utils.c.i

utils/gl_utils.s: utils/gl_utils.c.s

.PHONY : utils/gl_utils.s

# target to generate assembly for a file
utils/gl_utils.c.s:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/utils/gl_utils.c.s
.PHONY : utils/gl_utils.c.s

warehouse.o: warehouse.c.o

.PHONY : warehouse.o

# target to build an object file
warehouse.c.o:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/warehouse.c.o
.PHONY : warehouse.c.o

warehouse.i: warehouse.c.i

.PHONY : warehouse.i

# target to preprocess a source file
warehouse.c.i:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/warehouse.c.i
.PHONY : warehouse.c.i

warehouse.s: warehouse.c.s

.PHONY : warehouse.s

# target to generate assembly for a file
warehouse.c.s:
	$(MAKE) -f CMakeFiles/sokoban.dir/build.make CMakeFiles/sokoban.dir/warehouse.c.s
.PHONY : warehouse.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sokoban"
	@echo "... level_reader.o"
	@echo "... level_reader.i"
	@echo "... level_reader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maths/maths.o"
	@echo "... maths/maths.i"
	@echo "... maths/maths.s"
	@echo "... objects/cube.o"
	@echo "... objects/cube.i"
	@echo "... objects/cube.s"
	@echo "... utils/gl_utils.o"
	@echo "... utils/gl_utils.i"
	@echo "... utils/gl_utils.s"
	@echo "... warehouse.o"
	@echo "... warehouse.i"
	@echo "... warehouse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

